### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by ingageco** [areo/capacitor-codepush#2]
Is this in development or currently working? And does it support using your own storage service / delivery outside of the MS Codepush service? Thanks for answering!

**Comment by iamporus** [comment]
Any update on this?

**Comment by iguilhermeluis** [comment]
Working? Any update on this?

**Comment by darron1217** [comment]
I tried this package but it seems not working.

**Comment by luchillo17** [comment]
Ionic native already supports code push, and supports both cordova and capacitor by using the cordova plugin, guess the nuances of using the cordova plugin inside capacitor have been taken care by the Ionic native plugin:
https://ionicframework.com/docs/native/code-push

**Comment by bazuka5801** [comment]
@luchillo17 How I can add it to non ionic project (ex. quasar)?
I can't find any sources of @ionic-native/code-push

**Comment by luchillo17** [comment]
I'm only aware of Ionic Native, it's a utility made by the Ionic team, if Quasar doesn't offer such a feature I would guess it's not supported since Capacitor by itself doesn't either as far as I'm aware.

This plugin looks abandoned to me, the last commit was on Apr 11, 2020, and this thread itself has received 0 responses...

Try your luck with other people's forks that we're forked from this one: 
![image](https://user-images.githubusercontent.com/9698639/125366019-eab0dd80-e33a-11eb-93ee-941c80d189c0.png)

**Comment by bazuka5801** [comment]
@luchillo17 I found good solution https://github.com/Clovel/capacitor-codepush/tree/03df1588a2be78606222c36ff0bd1bfe10d6045c

**Comment by alexcroox** [comment]
@bazuka5801 that's just a fork for a PR for https://github.com/mapiacompany/capacitor-codepush

That's the main one we are using now with Cap3 and works 👍

**Comment by vially** [comment]
Sorry for the silence on this. This project is no longer maintained but https://github.com/mapiacompany/capacitor-codepush seems to be a maintained fork so I recommend using that instead.
